# Generated by Django 6.0.3 on 2026-03-28 20:50

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('Restaurant', 'Restaurant'), ('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Homestay', 'Homestay'), ('Cafe', 'Cafe')], max_length=50)),
                ('fssai_license_number', models.CharField(max_length=200)),
                ('license_document', models.FileField(upload_to='licenses/')),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
                ('mobile', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('cuisine_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Kerala', 'Kerala'), ('South_indian', 'South Indian'), ('North_indian', 'North Indian'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Arabic', 'Arabic'), ('Continental', 'Continental'), ('Italian', 'Italian'), ('Thai', 'Thai'), ('Seafood', 'Seafood'), ('Fast_food', 'Fast Food'), ('Street_food', 'Street Food'), ('Bakery', 'Bakery'), ('Cafe', 'Cafe'), ('Multi_cuisine', 'Multi Cuisine')], max_length=135)),
                ('food_type', models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg'), ('Veg & Non Veg', 'Veg & Non Veg')], max_length=20)),
                ('menu_file', models.FileField(blank=True, null=True, upload_to='menus/')),
                ('total_rooms', models.IntegerField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('wifi', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('live_music', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('room_service', models.BooleanField(default=False)),
                ('breakfast_availabe', models.BooleanField(default=False)),
                ('restaurant_available', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('taxi_service', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='restaurant/sections/rooms/')),
                ('entrance_image', models.ImageField(blank=True, null=True, upload_to='restaurant/sections/entrance/')),
                ('cafeteria_image', models.ImageField(blank=True, null=True, upload_to='restaurant/sections/cafeteria/')),
                ('parking_image', models.ImageField(blank=True, null=True, upload_to='restaurant/sections/parking/')),
                ('activities_image', models.ImageField(blank=True, null=True, upload_to='restaurant/sections/activities/')),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('rooms', 'Rooms'), ('entrance', 'Entrance'), ('cafeteria', 'Cafeteria'), ('parking', 'Parking'), ('activities', 'Activities')], max_length=50)),
                ('image', models.ImageField(upload_to='restaurant_gallery/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='restaurants.restaurantprofile')),
            ],
        ),
    ]
