# Generated by Django 6.0.3 on 2026-04-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurantprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='avg_cost_per_person',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='category',
            field=models.CharField(choices=[('stay', 'Stay'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('both', 'Stay + Food')], default='restaurant', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='price_level',
            field=models.IntegerField(choices=[(1, 'Budget'), (2, 'Mid'), (3, 'Luxury')], default=2),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='recommended_for',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
