# Generated by Django 6.0.3 on 2026-05-23 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantprofile_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='restaurantprofile',
            old_name='room_service',
            new_name='has_room_service',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='activities_image',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='air_conditioning',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='avg_cost_per_person',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='breakfast_availabe',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='cafeteria_image',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='checkin_time',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='checkout_time',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='entrance_image',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='live_music',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='menu_file',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='parking_image',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='price_level',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='recommended_for',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='restaurant_available',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='room_image',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='swimming_pool',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='taxi_service',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='total_rooms',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='wifi',
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='has_table_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='nearby_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='room_booking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='table_booking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField(default=1)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('special_request', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='restaurants.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variant', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non AC')], max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_guests', models.IntegerField(default=2)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='restaurants.restaurantprofile')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='restaurants.roomtype'),
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('rooms', 'Rooms'), ('dining', 'Dining Area'), ('reception', 'Reception'), ('parking', 'Parking'), ('pool', 'Pool'), ('entrance', 'Entrance'), ('activities', 'Activities'), ('bathroom', 'Bathroom'), ('gym', 'Gym'), ('spa', 'Spa'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='property_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='restaurants.restaurantprofile')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_sqft', models.IntegerField(blank=True, null=True)),
                ('view', models.CharField(blank=True, max_length=100)),
                ('bed_type', models.CharField(blank=True, max_length=100)),
                ('bathrooms', models.IntegerField(default=1)),
                ('about_room', models.TextField(blank=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('other_amenities', models.TextField(blank=True)),
                ('wifi', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('couple_friendly', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('bathroom', models.BooleanField(default=True)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('mineral_water', models.BooleanField(default=False)),
                ('laundry_service', models.BooleanField(default=False)),
                ('housekeeping', models.BooleanField(default=False)),
                ('in_room_dining', models.BooleanField(default=False)),
                ('iron_ironing_board', models.BooleanField(default=False)),
                ('room_service', models.BooleanField(default=False)),
                ('room_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='restaurants.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=2)),
                ('zone', models.CharField(blank=True, help_text='e.g. Indoor, Outdoor, Rooftop, VIP', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_reservable', models.BooleanField(default=True)),
                ('table_type', models.CharField(choices=[('normal', 'Normal'), ('family', 'Family'), ('couple', 'Couple'), ('vip', 'VIP'), ('private', 'Private')], default='normal', max_length=20)),
                ('dietary_type', models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non Veg'), ('both', 'Veg & Non Veg')], default='both', max_length=20)),
                ('cuisine_tags', models.CharField(blank=True, help_text='Comma separated or future M2M (e.g. Kerala, Chinese)', max_length=200)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_music', models.BooleanField(default=False)),
                ('has_view', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('slot_duration_minutes', models.IntegerField(default=90)),
                ('max_prebooking_days', models.IntegerField(default=30)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('guests', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('max_capacity', models.IntegerField(default=1)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='restaurants.table')),
            ],
        ),
        migrations.DeleteModel(
            name='RestaurantGallery',
        ),
    ]
