# Generated by Django 6.0.3 on 2026-05-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='table',
            name='booking_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.IntegerField(default=80, help_text='Table height in pixels'),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.IntegerField(default=0, help_text='X coordinate on floor plan (0-1000)'),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.IntegerField(default=0, help_text='Y coordinate on floor plan (0-1000)'),
        ),
        migrations.AddField(
            model_name='table',
            name='rotation',
            field=models.IntegerField(default=0, help_text='Rotation in degrees (0-360)'),
        ),
        migrations.AddField(
            model_name='table',
            name='section_name',
            field=models.CharField(blank=True, help_text='e.g., Window, Bar, Garden, VIP Area', max_length=50),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('circle', 'Circle'), ('square', 'Square'), ('rectangle', 'Rectangle'), ('round', 'Round')], default='square', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.IntegerField(default=80, help_text='Table width in pixels'),
        ),
    ]
