# Generated by Django 6.0.3 on 2026-05-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_table_average_rating_table_booking_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='table',
            name='cuisine_tags',
        ),
        migrations.RemoveField(
            model_name='table',
            name='dietary_type',
        ),
        migrations.RemoveField(
            model_name='table',
            name='max_prebooking_days',
        ),
        migrations.RemoveField(
            model_name='table',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='table',
            name='slot_duration_minutes',
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='cuisine_tags',
            field=models.CharField(blank=True, help_text='Comma separated (e.g. Kerala, Chinese, Italian)', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='default_max_prebooking_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='default_slot_duration_minutes',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='dietary_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non Veg'), ('both', 'Veg & Non Veg')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
