# Generated by Django 6.0.3 on 2026-05-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_table_closing_time_remove_table_cuisine_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='section',
            field=models.CharField(choices=[('rooms', 'Rooms'), ('dining', 'Dining Area'), ('reception', 'Reception'), ('parking', 'Parking'), ('pool', 'Pool'), ('entrance', 'Entrance'), ('activities', 'Activities'), ('bathroom', 'Bathroom'), ('gym', 'Gym'), ('spa', 'Spa'), ('menu', 'Menu'), ('other', 'Other')], max_length=30),
        ),
    ]
