# Generated by Django 6.0.3 on 2026-06-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_remove_roomtypedetail_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='table_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.tablebooking'),
        ),
    ]
