# Generated by Django 6.0.3 on 2026-06-02 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_payment_table_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='special_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
