# Generated by Django 6.0.3 on 2026-06-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_tablebooking_created_at_tablebooking_special_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
