# Generated by Django 6.0.3 on 2026-06-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_roombooking_platform_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
