# Generated by Django 6.0.3 on 2026-05-16 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='destinations/')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('best_season', models.CharField(blank=True, max_length=100)),
                ('best_months', models.CharField(blank=True, help_text='Example: October to February', max_length=200)),
                ('base_popularity', models.FloatField(default=50)),
                ('seasonal_score', models.FloatField(default=50)),
                ('usage_score', models.FloatField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_itinerary_usage', models.PositiveIntegerField(default=0)),
                ('total_bookmarks', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='places/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_hidden_gem', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, help_text='Beach, Waterfall, Trek, Temple, Hill Station etc', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('how_to_reach', models.TextField(blank=True)),
                ('road_condition', models.CharField(blank=True, help_text='Good road, Offroad, Trek required etc', max_length=200)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('best_time_of_day', models.CharField(blank=True, help_text='Sunrise, Sunset, Morning, Night', max_length=100)),
                ('best_months_to_visit', models.CharField(blank=True, max_length=200)),
                ('avg_visit_duration', models.IntegerField(default=120, help_text='In minutes')),
                ('crowd_level', models.CharField(blank=True, help_text='Low, Medium, High', max_length=100)),
                ('best_for_photography', models.BooleanField(default=False)),
                ('best_for_sunrise', models.BooleanField(default=False)),
                ('best_for_sunset', models.BooleanField(default=False)),
                ('things_to_do', models.TextField(blank=True, help_text='Comma separated')),
                ('activities', models.TextField(blank=True, help_text='Example: Boating, Hiking')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('parking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('suitable_for', models.CharField(blank=True, choices=[('family', 'Family'), ('couple', 'Couple'), ('solo', 'Solo'), ('friends', 'Friends'), ('kids', 'Kids'), ('adventure', 'Adventure Lovers'), ('photography', 'Photography Lovers')], max_length=100)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('travel_tips', models.TextField(blank=True)),
                ('safety_tips', models.TextField(blank=True)),
                ('things_to_carry', models.TextField(blank=True, help_text='Water bottle, Trek shoes etc')),
                ('rating', models.FloatField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('activity_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration', models.CharField(blank=True, help_text='30 mins, 2 hours etc', max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_activities', to='destinations.destinationplace')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place_gallery/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='destinations.destinationplace')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.destinationplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
