# Generated by Django 6.0.3 on 2026-04-14 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('best_season', models.CharField(help_text='Example: October - March', max_length=200)),
                ('best_months', models.CharField(help_text='Comma separated months', max_length=200)),
                ('tags', models.CharField(help_text='beach, hill-station, adventure, honeymoon, pilgrimage', max_length=255)),
                ('avg_budget_per_day', models.IntegerField(blank=True, null=True)),
                ('how_to_reach', models.TextField()),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('priority_score', models.IntegerField(default=1)),
                ('average_time_needed', models.IntegerField(help_text='Time in minutes')),
                ('entry_fee', models.IntegerField(default=0)),
                ('best_time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('any', 'Any')], default='any', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destinations.destination')),
            ],
        ),
    ]
