# Generated by Django 6.0.3 on 2026-05-16 21:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationplace',
            old_name='rating',
            new_name='average_rating',
        ),
        migrations.RenameField(
            model_name='placeactivity',
            old_name='activity_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='best_months',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='total_bookmarks',
        ),
        migrations.RemoveField(
            model_name='destinationplace',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='destinationplace',
            name='image',
        ),
        migrations.AddField(
            model_name='destination',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_month',
            field=models.CharField(blank=True, choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinationplace',
            name='nearest_transport',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='placeactivity',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_season',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='destinationplace',
            name='avg_visit_duration',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='destinationplace',
            name='best_time_of_day',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='destinationplace',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='destinationplace',
            name='crowd_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='destinationplace',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='destinationplace',
            name='road_condition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='destinationplace',
            name='suitable_for',
            field=models.CharField(choices=[('family', 'Family'), ('couples', 'Couples'), ('solo', 'Solo'), ('friends', 'Friends'), ('adventure', 'Adventure'), ('all', 'All')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='destinationplace',
            name='things_to_carry',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='destinationplace',
            name='things_to_do',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='placeactivity',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='placeactivity',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='placeactivity',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destinationplace'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='places/'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destinationplace'),
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destination')),
            ],
        ),
    ]
