# Generated by Django 6.0.3 on 2026-04-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_best_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='best_months',
        ),
        migrations.AddField(
            model_name='attraction',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='experience_type',
            field=models.CharField(blank=True, help_text='adventure, trekking, relaxed, spiritual, nightlife', max_length=100),
        ),
        migrations.AddField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attractions/'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='suitable_for',
            field=models.CharField(blank=True, help_text='family, friends, couples, solo', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='best_time_of_day',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('any', 'Any')], default='any', max_length=50),
        ),
    ]
