# Generated by Django 6.0.3 on 2026-05-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_rename_rating_destinationplace_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='best_month',
        ),
        migrations.AddField(
            model_name='destination',
            name='best_months',
            field=models.TextField(blank=True, help_text='e.g., November to February, or Jan,Feb,Mar'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring (March - May)'), ('summer', 'Summer (June - August)'), ('autumn', 'Autumn (September - November)'), ('winter', 'Winter (December - February)'), ('year_round', 'Year Round')], max_length=50),
        ),
    ]
