# Generated by Django 6.0.3 on 2026-04-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_destination_best_months_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attraction',
            unique_together={('destination', 'name')},
        ),
    ]
