# Generated by Django 6.0.3 on 2026-05-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_destination_best_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='popularity_score',
            field=models.FloatField(default=0, help_text='Auto-calculated popularity score'),
        ),
        migrations.AddField(
            model_name='destination',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='Higher score = higher priority (0-100)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='recommended_visit_order',
            field=models.IntegerField(default=0, help_text='Order in which to visit (1,2,3...)'),
        ),
    ]
