# Generated by Django 6.0.3 on 2026-05-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_popularity_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='base_popularity',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='best_months',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='priority_score',
        ),
        migrations.AddField(
            model_name='destination',
            name='best_month_end',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_month_start',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='destination',
            name='current_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='final_trending_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='last_weather_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='manual_priority_score',
            field=models.FloatField(default=10, help_text='Admin controlled priority score'),
        ),
        migrations.AddField(
            model_name='destination',
            name='preferred_weather',
            field=models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('cold', 'Cold'), ('rainy', 'Rainy'), ('snow', 'Snow'), ('cloudy', 'Cloudy')], max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='weather_score',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='destinationplace',
            name='final_trending_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='destinationplace',
            name='manual_priority_score',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='destinationplace',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='destinationplace',
            name='preferred_weather',
            field=models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('cold', 'Cold'), ('rainy', 'Rainy'), ('snow', 'Snow'), ('cloudy', 'Cloudy')], max_length=50),
        ),
        migrations.AddField(
            model_name='destinationplace',
            name='weather_score',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('year_round', 'Year Round')], max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='recommended_visit_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='seasonal_score',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
