# Generated by Django 6.0.3 on 2026-04-18 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_attraction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='activities',
            field=models.CharField(blank=True, help_text='jet ski, trekking, cruise, nightlife', max_length=255),
        ),
        migrations.AddField(
            model_name='attraction',
            name='best_months',
            field=models.CharField(blank=True, help_text='e.g. Oct-Mar', max_length=100),
        ),
        migrations.AddField(
            model_name='attraction',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], max_length=20),
        ),
        migrations.AddField(
            model_name='attraction',
            name='distance_from_city',
            field=models.FloatField(blank=True, help_text='Distance in KM', null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='extra_cost_per_person',
            field=models.IntegerField(default=0, help_text='Jeep safari, cruise, activities etc'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='group_cost',
            field=models.IntegerField(default=0, help_text='Cost for group activities'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='important_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='is_night_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attraction',
            name='nearest_transport',
            field=models.CharField(blank=True, help_text='Nearest airport/railway', max_length=255),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='experience_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='suitable_for',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AttractionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='destinations.attraction')),
            ],
        ),
    ]
