# Generated by Django 6.0.3 on 2026-05-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_remove_destination_base_popularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationplace',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='Higher score = higher priority (0-100)'),
        ),
    ]
