# Generated by Django 6.0.3 on 2026-05-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_destinationplace_priority_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationplace',
            name='nearest_transport',
        ),
        migrations.RemoveField(
            model_name='destinationplace',
            name='road_condition',
        ),
    ]
