# Generated by Django 6.0.3 on 2026-05-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_remove_destinationplace_nearest_transport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationplace',
            name='priority_score',
        ),
        migrations.AddField(
            model_name='destination',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='destinationplace',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='destinationplace',
            name='seasonal_score',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='destination',
            name='manual_priority_score',
            field=models.FloatField(default=10, help_text='Admin/User controlled importance score (0-20)'),
        ),
    ]
