# Generated by Django 6.0.3 on 2026-04-17 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CustomizedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_data', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
