# Generated by Django 6.0.3 on 2026-06-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_role',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
