# Generated by Django 6.0.1 on 2026-02-25 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
