# Generated by Django 6.0.1 on 2026-02-25 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='activities_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/sections/activities/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='cafeteria_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/sections/cafeteria/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='entrance_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/sections/entrance/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='parking_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/sections/parking/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/sections/rooms/'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
