# Generated by Django 6.0.1 on 2026-02-25 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurantprofile_activities_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('rooms', 'Rooms'), ('entrance', 'Entrance'), ('cafeteria', 'Cafeteria'), ('parking', 'Parking'), ('activities', 'Activities')], max_length=20)),
                ('image', models.ImageField(upload_to='restaurant/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='restaurants.restaurantprofile')),
            ],
        ),
    ]
