# Generated by Django 5.2.5 on 2026-03-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='activities_image',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='cafeteria_image',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='entrance_image',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='parking_image',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='room_image',
        ),
    ]
