# Generated by Django 5.2.5 on 2026-03-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurantprofile_activities_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='activities_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/sections/activities/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='cafeteria_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/sections/cafeteria/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='entrance_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/sections/entrance/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='parking_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/sections/parking/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/sections/rooms/'),
        ),
    ]
