# Generated by Django 5.2.5 on 2026-03-05 10:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantprofile_activities_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='food_type',
            field=models.CharField(blank=True, choices=[('veg', 'Veg'), ('nonveg', 'Non Veg'), ('both', 'Both')], max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='menu_file',
            field=models.FileField(blank=True, null=True, upload_to='menus/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='price_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='property_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('resort', 'Resort'), ('homestay', 'Homestay'), ('cafe', 'Cafe')], max_length=50),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='total_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='fssai_license_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='license_document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='licenses/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='place_id_proof',
            field=models.FileField(default=django.utils.timezone.now, upload_to='id_proofs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
