# Generated by Django 5.2.5 on 2026-03-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_restaurantprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='cuisine_type',
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='cuisine_type',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.cuisine'),
        ),
    ]
