# Generated by Django 5.2.5 on 2026-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_cuisine_remove_restaurantprofile_cuisine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='cuisine_type',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('kerala', 'Kerala'), ('south_indian', 'South Indian'), ('north_indian', 'North Indian'), ('indian', 'Indian'), ('chinese', 'Chinese'), ('arabic', 'Arabic'), ('continental', 'Continental'), ('italian', 'Italian'), ('thai', 'Thai'), ('seafood', 'Seafood'), ('fast_food', 'Fast Food'), ('street_food', 'Street Food'), ('bakery', 'Bakery'), ('cafe', 'Cafe'), ('multi_cuisine', 'Multi Cuisine')], max_length=30),
        ),
    ]
