# Generated by Django 5.2.5 on 2026-03-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_remove_restaurantprofile_cuisine_type_delete_cuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='breakfast_availabe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='live_music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurant_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='room_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='room_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='taxi_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('Kerala', 'Kerala'), ('South_indian', 'South Indian'), ('North_indian', 'North Indian'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Arabic', 'Arabic'), ('Continental', 'Continental'), ('Italian', 'Italian'), ('Thai', 'Thai'), ('Seafood', 'Seafood'), ('Fast_food', 'Fast Food'), ('Street_food', 'Street Food'), ('Bakery', 'Bakery'), ('Cafe', 'Cafe'), ('Multi_cuisine', 'Multi Cuisine')], max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='food_type',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg'), ('Veg & Non Veg', 'Veg & Non Veg')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Restaurant', 'Restaurant'), ('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Homestay', 'Homestay'), ('Cafe', 'Cafe')], max_length=50),
        ),
    ]
