# Generated by Django 6.0.3 on 2026-05-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_destination_destinationplace_placereview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationplace',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='travelstory',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='shareditinerary',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='destinationplace',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='placereview',
            name='place',
        ),
        migrations.RemoveField(
            model_name='placereview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shareditinerary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='travelstory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='DestinationPlace',
        ),
        migrations.DeleteModel(
            name='PlaceReview',
        ),
        migrations.DeleteModel(
            name='SharedItinerary',
        ),
        migrations.DeleteModel(
            name='TravelStory',
        ),
    ]
