# Generated by Django 6.0.3 on 2026-05-22 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_destinationplace_destination_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('travellers', '0005_buddyrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='buddy_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travellers.buddyrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('join_request', 'Join Request'), ('request_approved', 'Request Approved'), ('trip_update', 'Trip Update'), ('post_like', 'Post Like'), ('comment', 'Comment'), ('poll_vote', 'Poll Vote'), ('booking', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('trip_completed', 'Trip Completed'), ('buddy_request', 'Buddy Request'), ('buddy_request_accepted', 'Buddy Request Accepted'), ('profile_like', 'Profile Post Like'), ('profile_comment', 'Profile Post Comment'), ('follow', 'New Follower')], max_length=25),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
