# Generated by Django 6.0.3 on 2026-05-25 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('join_request', 'Join Request'), ('request_approved', 'Request Approved'), ('trip_update', 'Trip Update'), ('post_like', 'Post Like'), ('comment', 'Comment'), ('poll_vote', 'Poll Vote'), ('booking', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('trip_completed', 'Trip Completed'), ('buddy_request', 'Buddy Request'), ('buddy_request_accepted', 'Buddy Request Accepted'), ('buddy_request_rejected', 'Buddy Request Rejected'), ('profile_like', 'Profile Post Like'), ('profile_comment', 'Profile Post Comment'), ('follow', 'New Follower')], max_length=25),
        ),
    ]
