# Generated by Django 6.0.3 on 2026-05-27 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_community_is_active_post_created_at_post_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='join_type',
            field=models.CharField(choices=[('approval', 'Approval Required'), ('direct', 'Direct Join')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='live_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='visibility',
            field=models.CharField(choices=[('community', 'Community'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='tripparticipant',
            name='is_location_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripparticipant',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('coordinator', 'Coordinator')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='community.community'),
        ),
        migrations.AlterUniqueTogether(
            name='tripparticipant',
            unique_together={('trip', 'user')},
        ),
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='community.tripparticipant')),
            ],
        ),
    ]
