# Generated by Django 6.0.3 on 2026-06-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_message_options_message_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('join_request', 'Join Request'), ('request_approved', 'Request Approved'), ('trip_update', 'Trip Update'), ('post_like', 'Post Like'), ('comment', 'Comment'), ('poll_vote', 'Poll Vote'), ('booking', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('trip_completed', 'Trip Completed'), ('buddy_request', 'Buddy Request'), ('buddy_request_accepted', 'Buddy Request Accepted'), ('buddy_request_rejected', 'Buddy Request Rejected'), ('profile_like', 'Profile Post Like'), ('profile_comment', 'Profile Post Comment'), ('follow', 'New Follower'), ('destination_approved', 'Destination Approved'), ('destination_rejected', 'Destination Rejected'), ('place_approved', 'Place Approved'), ('place_rejected', 'Place Rejected'), ('message', 'Message')], max_length=25),
        ),
    ]
