# Generated by Django 6.0.3 on 2026-03-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_verified_customuser_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_approved',
            new_name='is_verified',
        ),
    ]
