"""
Django settings for wayzo project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qo+46=qst*-mxo_lrr4*gc4r3d8=$4dlo3s2q%e+*(-2jnh)#z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'templates' / 'accounts' / 'static',
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agencies',
    'restaurants',
    'travellers',
     'accounts',
     'admin_app',
     'multiselectfield',
     'community',
     'planner',
     'destinations',
     "support",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wayzo.urls'
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'travellers.context_processors.user_profile_context',
                'travellers.context_processors.unread_messages_count',
                'travellers.context_processors.buddy_pending_count',
                'admin_app.context_processors.admin_notifications',
                'community.context_processors.notification_counts',
                'support.context_processors.complaint_counts',
            ],
            'libraries':{
                'custom_filters': 'templatetags.custom_filters',
            }
        },
    },
]

WSGI_APPLICATION = 'wayzo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/



AUTH_USER_MODEL = 'accounts.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'

import os
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

# ================= API KEYS =================
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
SERPAPI_KEY = os.getenv("SERPAPI_KEY")
GEONAMES_USERNAME = os.getenv("GEONAMES_USERNAME")
OPENTRIPMAP_KEY = os.getenv("OPENTRIPMAP_KEY")
OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY")
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")


# 🔒 Validate keys properly
if not GROQ_API_KEY:
    raise ValueError("❌ GROQ_API_KEY not set in environment")

if not GOOGLE_API_KEY:
    print("⚠️ WARNING: GOOGLE_API_KEY not set (Places/Maps may fail)")

# =====================================================
# GROQ CLIENT (AI)
# =====================================================

client = Groq(api_key=GROQ_API_KEY)

# Default model (centralized)
GROQ_MODEL = "llama3-70b-8192"


# =====================================================
# CACHE CONFIG (DJANGO)
# =====================================================

# NOTE:
# This should ideally be in settings.py,
# but keeping here if you're using it as a shared config module.

try:
    CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}
except Exception:
    print("⚠️ Redis not available → using local memory cache")
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "wayzo-cache",
        }
    }


# =====================================================
# CACHE DURATIONS (seconds)
# =====================================================

CACHE_DURATIONS = {
    "attractions": 60 * 60 * 24 * 7,   # 7 days
    "weather": 60 * 60 * 6,            # 6 hours
    "itinerary": 60 * 60 * 24,         # 24 hours
}
