# Generated by Django 6.0.3 on 2026-03-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='group_size',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='accommodation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='drop_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='exclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='inclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='max_group_size',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meals',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='min_group_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='pickup_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='suitable_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='things_to_carry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='transport_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
