# Generated by Django 6.0.3 on 2026-03-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_remove_tourpackage_group_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
