# Generated by Django 6.0.3 on 2026-03-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_tourpackage_is_active_tourpackage_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
