# Generated by Django 6.0.3 on 2026-03-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_tourpackage_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_package/gallery/'),
        ),
    ]
