# Generated by Django 6.0.3 on 2026-03-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_alter_packageimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tour_package/icons/'),
        ),
    ]
