# Generated by Django 6.0.3 on 2026-03-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_tourpackage_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='max_group_size',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='min_group_size',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
