# Generated by Django 6.0.3 on 2026-03-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_alter_tourpackage_max_group_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='icon',
        ),
    ]
