# Generated by Django 6.0.3 on 2026-03-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_remove_tourpackage_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='travellers_count',
            field=models.PositiveIntegerField(),
        ),
    ]
