# Generated by Django 6.0.3 on 2026-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_packagebooking_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='best_season',
            field=models.CharField(blank=True, help_text='e.g., October to March, Summer Months, Throughout the year', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('difficult', 'Difficult')], default='moderate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='max_booking_days',
            field=models.PositiveIntegerField(blank=True, default=365, help_text='Maximum days before travel to book this package', null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='min_booking_days',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Minimum days before travel to book this package', null=True),
        ),
    ]
