# Generated by Django 6.0.3 on 2026-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0011_tourpackage_best_season_tourpackage_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebooking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('agency', 'Agency'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='refund_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
