# Generated by Django 6.0.3 on 2026-04-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0012_packagebooking_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
