# Generated by Django 6.0.3 on 2026-04-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0013_alter_packagebooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
