# Generated by Django 6.0.3 on 2026-05-22 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0015_packagebooking_approval_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebooking',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='refund_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='refund_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Refund Pending'), ('processing', 'Processing'), ('success', 'Refund Successful'), ('failed', 'Refund Failed')], default='not_applicable', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('gateway_ref_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='agencies.packagebooking')),
            ],
        ),
    ]
