# Generated by Django 6.0.3 on 2026-04-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='end_location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='end_time',
            field=models.TimeField(default='21:00'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='start_location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='pace',
            field=models.CharField(choices=[('slow', 'Relaxed'), ('medium', 'Balanced'), ('fast', 'Aggressive')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='transport_mode',
            field=models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('car', 'Car'), ('bike', 'Bike'), ('walk', 'Walk')], default='car', max_length=50),
        ),
    ]
