# Generated by Django 6.0.3 on 2026-04-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='transport_mode',
            field=models.CharField(choices=[('any', 'Any'), ('walking', 'Walking'), ('public', 'Public Transport'), ('taxi', 'Taxi'), ('car', 'Car'), ('bike', 'bike')], default='any', max_length=30),
        ),
    ]
