# Generated by Django 6.0.3 on 2026-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0002_travelplan_end_latitude_travelplan_end_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='activity_types',
            field=models.CharField(blank=True, help_text='e.g. sightseeing, trekking, beach', max_length=200),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='auto_book_restaurants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='auto_book_stays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='avoid_long_travel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='crowd_preference',
            field=models.CharField(choices=[('low', 'Less crowded'), ('medium', 'Balanced'), ('high', 'Lively')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='cuisine_preference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='daily_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='food_preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('any', 'Any')], default='any', max_length=50),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='has_elderly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='max_travel_distance_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='In KM', null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='meal_budget',
            field=models.CharField(choices=[('low', 'Budget'), ('medium', 'Moderate'), ('high', 'Premium')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='must_visit_places',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='needs_accessibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='nightlife_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='prefer_indoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='rain_flexible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='room_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], max_length=50),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='stay_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('homestay', 'Homestay'), ('hostel', 'Hostel'), ('any', 'Any')], default='any', max_length=50),
        ),
    ]
