# Generated by Django 6.0.3 on 2026-04-29 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0002_alter_travelplan_transport_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travellers.travelplan')),
            ],
        ),
    ]
