# Generated by Django 6.0.3 on 2026-05-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0003_generateditinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='GeneratedItinerary',
        ),
        migrations.DeleteModel(
            name='TravelPlan',
        ),
    ]
