# Generated by Django 6.0.3 on 2026-05-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0006_remove_propertybooking_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travellerprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='travellerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='traveller_covers/'),
        ),
    ]
