# Generated by Django 6.0.3 on 2026-05-25 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0007_remove_travellerprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepostlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
