# Generated by Django 6.0.3 on 2026-05-26 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0017_packagebooking_agency_earnings_and_more'),
        ('restaurants', '0008_restaurantprofile_avg_rating_and_more'),
        ('travellers', '0008_profilepostlike_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurantprofile'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.tourpackage'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'package'), ('user', 'restaurant')},
        ),
    ]
