# Generated by Django 6.0.3 on 2026-06-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0009_wishlist_restaurant_alter_wishlist_package_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyBooking',
        ),
    ]
