# Generated by Django 6.0.3 on 2026-04-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='TripRequest',
        ),
    ]
