# Generated by Django 6.0.3 on 2026-05-08 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='estimated_budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='pdf_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='share_token',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='traveler_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='traveler_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='activity_level',
            field=models.CharField(choices=[('relaxed', 'Relaxed'), ('moderate', 'Moderate'), ('active', 'Active')], default='moderate', max_length=50),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='budget',
            field=models.CharField(choices=[('budget', 'Budget'), ('mid_range', 'Mid Range'), ('luxury', 'Luxury')], default='mid_range', max_length=30),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='food_preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('any', 'Any')], default='any', max_length=50),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='hotel_stars',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='hotel_type',
            field=models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('villa', 'Villa'), ('hostel', 'Hostel'), ('homestay', 'Homestay')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='include_hidden_gems',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='include_local_food',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='include_nightlife',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='include_shopping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Wheelchair accessibility, kids friendly, honeymoon trip, photography spots etc.', null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='transport_mode',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('walking', 'Walking'), ('public_transport', 'Public Transport'), ('mixed', 'Mixed')], default='mixed', max_length=50),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='traveler_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='traveler_type',
            field=models.CharField(choices=[('solo', 'Solo Traveler'), ('couple', 'Couple'), ('family', 'Family'), ('friends', 'Friends Group'), ('business', 'Business')], default='solo', max_length=50),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='trip_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='planner.triprequest'),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='interests',
            field=models.TextField(help_text='nature, beaches, adventure, nightlife, culture, food, trekking etc.'),
        ),
    ]
