# Generated by Django 6.0.3 on 2026-05-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_itinerary_estimated_budget_itinerary_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='ending_place',
            field=models.CharField(blank=True, help_text='Trip ending location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='starting_place',
            field=models.CharField(blank=True, help_text='Trip starting location', max_length=255, null=True),
        ),
    ]
